travis:
  secure:
    BINSTAR_TOKEN: ddz2pcAikCP9ZwkLjsfnisFR+OfQJ8VHa2MhYaSTihKq9UAEtd1nmPwgBxx4qJaJUQ04TPfBcGTH6FZPVEt+VYTDGCyS3xUy0a0VxORD1hKy7ILqRSfnidKOs2uEdAPXDHCCranyj13067rSt+ytJfxfhmnWJCqGXXHVKiYJ7HcLgsgMjPLm6b4PPKZhz1s+mzix5Tjm4PXyPlxnGQywBH4vymEq2i+SF1bcsmp7iYJXfHCzDckhzAW5ZYyLp/r/J97Pti9c9jumSMReZWswNvZZrQckFQaVNIuk+FGKl6bO0KmeH6ucQbD1ssd5jD+m+MjnVTlc2XpPQkHVqSkZtG1PLK3OUHq14/AqEz5JXSLGU02+3Ln4macYvTsBiZfNxEK0YWyMzoRBtCVQOaSrKt+fHf4LIRcOtRYWAgSlLdAVu8yj6uGMUpBxD88kzygZlZ4fNZXncg8i1Kyye79uogk3xwA5fizN0ZN126uWa96d8rdmkldd4baEutVhmWTBGuXzzEyOWgiAUiyaw/CYIRRFvnwH1G/ZFCsXamG+cJaC5LdpTJLTai78Nk9sjsduIxTH50ILDI08WhS9jxkKpUHvHey6+DJHmgbiWZcDkM7NiXaWzLQlf6d++UwqAK+iUEQRuoW4PzP4/J7ZPlAuwCtOw7gZd8NXdJS03903R1c=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
