travis:
  secure:
    BINSTAR_TOKEN: OmeW8XUPlB6HdUaLClPK1Y82iMPFKpLrOvGxpzjLx1+g88IxIeMWoIhVZf9sSyr8yATesaC/0v2NioEyEvpA22BBdkqARtW2kE7yiiiUM5VHJNY8JST2uKcrhzXvXQ0dhCq2j8BRRAj4oI19IM4gUbh0VQD2JCHk9oXJtxr5O3OyHXNVnrka3UjI3tpXxe5pNahBYqi2K9PLeifV57f56TEm7+GN275BOtwL5TmuSz7jjp6cSHTWzwxPKFUwe69zZs//0vqlOIudRADG1QuRcrSzEi8rTHo4S4OLF+0Lf4v55dBY6R7bHG2hDzjMYYL2l8H6xLbOO79STkBAhAi1D8+SNOo4Y0n70/WVtZhMbiMLIYz6AphOJU6MgrNrMf5z94oeaLF4tF8dqUVn9BWZ7m3brav+E9sDDdlDNCwOvVRRVug7Lv3a5u59KENIkkKvTwVe5MwJXQ4VQ9sTxIPHYlH0lorlFcbuQ+4jtkvCpqOJfOWJybLIaUWJFTLtSBoZHWohdbiErj75QauoVWv+mD+/8f3NqFVAWEGBwBGSACBh4dV1SRKiNgkG/BcctCDR5eE6l1XNvKYPvS2XvUtqoQGp17pMpEfE0XDd81UiTlY7NgmTDQt3T6Hg0nLoVMlJnOrubmONYJAkNnI8oCCC54WugRWsS4bIFAeT3PSXKvE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
